# Generated by Django 5.0.1 on 2024-01-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_detailnews_short_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='detailnews',
            options={'verbose_name_plural': 'Detail News'},
        ),
        migrations.AlterModelOptions(
            name='shortnews',
            options={'verbose_name_plural': 'Short News'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
