# Generated by Django 5.0.1 on 2024-01-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_categories_options_alter_detailnews_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_number',
            field=models.IntegerField(null=True),
        ),
    ]
